- name: setup cp4 project
  hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Update packages and their dependancies
      apt:
        update_cache: false
        name:
          - python3
          - python-apt
          - python3-pip
          - nginx
          - virtualenv
          - git
          - software-properties-common
          - python-certbot-nginx
        state: present

    - name: Check if the repo has been cloned before
      stat:
        path: /home/vagrant/stackoverflowlite
      register: repo

    - name: Clone the repo and setup files
      shell: git clone https://github.com/MartinKaburu/stackoverflowlite.git;
      when: repo.stat.exists == False

    - name: Remove the default config file if it exists
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create link
      file:
        src: /etc/nginx/sites-available/app
        path: /etc/nginx/sites-enabled/app
        state: link
        force: true
        follow: false

    - name: Configure Nginx
      shell: |
              bash -c "cat > /etc/nginx/sites-enabled/app <<END
              server {
                      server_name martinkaburu.info www.martinkaburu.info;
                      location / {
                              proxy_pass http://127.0.0.1:5000;
                      }
              }
              END"
              sudo /etc/init.d/nginx restart

    - name: Install and Setup SSL for the domain names using certbot
      shell: |
              certbot --nginx  -d martinkaburu.info -d www.martinkaburu.info -m martinkaburu.m@gmail.com --agree-tos --non-interactive
              /etc/init.d/nginx restart

    - name: Setup the applications virtual environment and install requirements
      shell:
            chdir:  /home/vagrant/stackoverflowlite
            cmd: |
                  virtualenv --python=python3 venv
                  source venv/bin/activate
                  pip3 install -r requirements.txt --user
                  python3 run.py
